version: '3'
services:

  # The Web Server
  curve-card:
    build: .
    volumes:
      - .:/var/www
    #working_dir: /var/www
    ports:
      - 8000:80
    environment:
        APP_ENV: local
        APP_DEBUG: 'true'
        APP_KEY: SomeRandomKey!!!
        APP_LOCALE: en
        APP_FALLBACK_LOCALE: en
        DB_CONNECTION: mysql
        DB_HOST: lumen-db
        DB_DATABASE: lumen
        DB_USERNAME: app
        DB_PASSWORD: password

  lumen-db:
    image: mysql:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: lumen
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password